version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: "nginx"
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - "80:80"
      - "82:82"
      - "443:443"
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /var/log/nginx:/var/log/nginx
      - /etc/hosts:/etc/hosts:ro
    depends_on:
      - fpm-73
  fpm-73:
    image: webdev:7.3-fpm
    build: 7.3/
    container_name: "7.3-fpm"
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    working_dir: /var/www
    volumes:
      - ./../:/var/www
      - /tmp:/tmp
      - /etc/hosts:/etc/hosts:ro
#  portainer:
#    image: portainer/portainer:latest
#    container_name: "portainer"
#    restart: always
#    ports:
#      - "81:9000"
#    command: -H unix:///var/run/docker.sock
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data

  mysql:
    image: mysql
    container_name: "mysql"
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: aceleradev
      MYSQL_ROOT_PASSWORD: Hta7827kb

volumes:
  portainer_data:
  my-db:
